### ISSUE TITLE
发现一个奇怪的错位问题

### ISSUE THREAD

**Issue by star4gmx** [pantaohe/worldoftank#2]
偶尔登录git发现之前缺包的issues被作者大大回复了，按照地址重新打包试了下，果然能跑起来。
但是在笔记本和家里的台式上验证发现一个有意思的现象。
笔记本3200 * 2000的分辨率（16:10），改成1920 * 1080分辨率后，上下存在黑边，但是程序运行正常，点击各个坐标的按钮也比较准确。
台式机，台式机是4k分辨率（16:9），改成1920 * 1080后，等比例不存在黑边，但是程序运行时，点击按钮反而会出现错位，各种点错到旁边的按钮上。又找了家里人的原生1920 * 1080分辨率的笔记本，试了下，现象一模一样。
遂过来反应下，等有空了无聊了再翻下代码bug下看看。

**Comment by pantaohe** [comment]
这个是屏幕 缩放与布局 调成了非100%

**Comment by star4gmx** [comment]
周末试了下还真是缩放的锅。
把旧笔记拿出来跑下，发现完全不想打了只想爬线，硬生生把竞技游戏变成了养成类游戏，感谢分享让我从已经完全放弃很多年的游戏里找回来了点原来的乐趣。

**Comment by star4gmx** [comment]
关闭
